### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/r-python-exercise1-utkarshapatil01#1]
Hi Utkarsha,

Great work on the assignment. Some minor feedback:

It's important to have authorship on all notebooks (first name, last name)
This changes makes the notebook more readable and shareable.

I am giving you full credit, contingent on you fixing these minor issues by September 15th.
-Greg

**Comment by utkarshapatil01** [comment]
Hi Professor,

Thank you for your feedback and for acknowledging the progress on the assignment. I appreciate your guidance. I've successfully resolved it by adding the author's name to the book, following your advice. 

Sincerely,
Utkarsha
